### ISSUE TITLE
Remove theme overrides

### ISSUE THREAD

**Issue by jenslind** [oddhill/oddbaby#1]
These two theme functions puts the `<input>` element inside the label, why?
https://github.com/oddhill/oddbaby/blob/master/theme.inc#L79
https://github.com/oddhill/oddbaby/blob/master/theme.inc#L156

Would be great if we could skip those functions.
Because right now you can't use the following, which sucks :eyeglasses:.

``` css
input[type=checkbox]:checked + label
```

**Comment by olofbokedal** [comment]
It was a while ago, but I think we added those in order to fix clickable input labels for older browsers. Probably no need for these overrides anymore, but we should test the browser behavior just in case.
